In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.20.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.1.2)

In [ ]:
from datasets import load_dataset

In [3]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers" , split= 'train')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [9]:
df=df[['title','abstract']]

In [10]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [11]:
df.shape

(117592, 2)

In [12]:
df=df.head(15000)

In [13]:
df.shape

(15000, 2)

In [15]:
df.isnull().sum()

title         0
abstract      0
paper_text    0
dtype: int64

In [14]:
df["paper_text"] = df["title"] + df["abstract"]

/tmp/ipykernel_20634/3297733390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"] = df["title"] + df["abstract"]

In [17]:
# Save the processed DataFrame to a pickle file, so main.py can load it.
df.to_pickle('df.pkl')
print("DataFrame saved to df.pkl")

DataFrame saved to df.pkl

In [16]:
type(df["paper_text"])

pandas.core.series.Series

In [18]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations  The pro...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [19]:
print(df["paper_text"].iloc[0])

Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [20]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.12.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.20.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [21]:
# Uninstall torchcodec to resolve compatibility issues with PyTorch and sentence-transformers
!pip uninstall -y torchcodec

# --- IMPORTANT: After this cell runs, you MUST RESTART THE COLAB RUNTIME (Runtime > Restart runtime) ---
# --- Then, run all cells from the beginning of the notebook.                                         ---

from sentence_transformers import SentenceTransformer
print("SentenceTransformer imported successfully!")

# Update dynamic linker run-time bindings (kept from previous attempt if still relevant after restart)
!ldconfig

# Instantiate a model to further confirm it's working
try:
    model_test = SentenceTransformer("all-MiniLM-L6-v2")
    print("SentenceTransformer model loaded successfully!")
except Exception as e:
    print(f"Error loading SentenceTransformer model: {e}")

WARNING: Skipping torchcodec as it is not installed.
SentenceTransformer imported successfully!
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

SentenceTransformer model loaded successfully!

In [22]:

model= SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [23]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [24]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [25]:
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_20634/2190359946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
/tmp/ipykernel_20634/2190359946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

In [26]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [27]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [28]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

In [29]:
sample_embedding=model.encode(df["paper_text"].head(5).to_list())

In [30]:
print(sample_embedding.shape)

(5, 384)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
similarity=cosine_similarity(sample_embedding[0].reshape(1, -1),sample_embedding[0].reshape(1, -1))
print(similarity)

[[1.0000001]]

In [34]:
similarity=cosine_similarity(sample_embedding[0].reshape(1, -1),sample_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]

In [33]:
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1, -1),sample_embedding[1].reshape(1, -1))
  print(sim)

[[0.36625272]]
[[0.36625272]]
[[0.36625272]]
[[0.36625272]]

Generate full embedding

In [35]:
import os
import numpy as np

if os.path.exists(" paper_embeddings.npy"):
  print("Loading saved embeddings")

  embeddings=np.load(" paper_embeddings.npy")
else:
  print("Generating embeddings" )

  embeddings=model.encode(
      df["paper_text"].to_list(),

      batch_size=32,
      show_progress_bar=True

  )
  np.save("paper_embeddings.npy",embeddings)

  print("Embeddings saved successfully!") #embeddings =model.encode(
      #df["paper_text"].tolist()
      #batch_size=32,
      #show_progress_bar=True
      #)==============

Generating embeddings

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

Embeddings saved successfully!

In [37]:
print(embedding.shape)
print(type(embedding))

(384,)
<class 'numpy.ndarray'>

In [38]:
embedding.dtype

dtype('float32')

In [36]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [39]:
import faiss

In [40]:
faiss.normalize_L2(embedding.reshape(1, -1))

In [41]:
index=faiss.IndexFlatIP(384)

In [42]:
if os.path.exists("paper_faiss.index"):
  print("Loading existing index")
  index=faiss.read_index("paper_faiss.index")
else:
  print("Creating new FAISS index")
  faiss.normalize_L2(embeddings)
  index=faiss.IndexFlatIP(384)
  index.add(embeddings)
  faiss.write_index(index,"paper_faiss.index")
  print("FAISS index saved successfully!")

Loading existing index

In [43]:
print(index.ntotal)

15000

In [44]:
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [45]:
faiss.normalize_L2(query_embedding)

In [46]:
D,I=index.search(query_embedding,5)
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [48]:
print(df.iloc[10466]["title"])

A Perspective on Deep Imaging

In [47]:
print(df.iloc[10466]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [49]:
print(df.iloc[11873]["title"])

Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

In [50]:
print(df.iloc[11873]["abstract"])

  The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).

In [51]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

In [52]:
D,I=search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [54]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Title",df.iloc[idx]['abstract'][:500])

In [55]:
search_paper("deep learning for medical image analysis")

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

In [56]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.12.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.20.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [57]:
from transformers import pipeline

# Initialize the text-generation pipeline with a suitable model like 'gpt2'
# We'll use this to approximate summarization since 'summarization' task was unavailable.
text_generator = pipeline("text-generation", model="gpt2")

print("Text generation pipeline initialized successfully!")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Text generation pipeline initialized successfully!

In [58]:
# Get the abstract to be summarized
abstract_to_summarize = df.iloc[10466]["abstract"]

# Use the text generator to create a summary. You might need to adjust parameters
# like max_length, num_return_sequences, and truncation based on desired output.
# Here, we'll try to generate a concise summary.
generated_summary = text_generator(
    abstract_to_summarize,
    max_length=150,  # Max length of the generated summary
    min_length=50,   # Min length of the generated summary
    num_return_sequences=1,
    truncation=True
)

print("Original Abstract (first 500 chars):")
print(abstract_to_summarize[:500])
print("\nGenerated Summary:")
print(generated_summary[0]['generated_text'])

[transformers] Passing `generation_config` together with generation-related arguments=({'num_return_sequences', 'max_length', 'min_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Original Abstract (first 500 chars):
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Generated Summary:
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

1. What is the purpose of imaging and the technique?

Machine learning is the process of transforming information to

new images and new images to new information. This process is

designed to change a person's personality. It is particularly applicable to

people who are in the presence of or working with a patient or

facilitator, or who are in a clinical setting, who have to overcome

difficult and often difficult behaviors and relationships with friends or family. The

purpose of the imaging technique is to change a person's personality and

mind-set. The imaging technique is the most effective

technique in the clinical imaging field to change a person's

life. It is a great way to identify a person's mood and

behavior, to help him or her understand their

attitudes and expectations, and to assess their health and health care

care outcomes.

2. What is the purpose of the technique?

The imaging technique is the process whereby the

image is transformed to new images by a computer program. The image

is transformed to new images when the computer program has

expanded its capabilities to accommodate different types of

images. These

In [59]:
generated_summary = text_generator(
    df.iloc[10466]["abstract"],
    max_length=120,
    min_length=40,
    num_return_sequences=1,
    truncation=True
)
print(generated_summary[0]['generated_text'])

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

The approach that is needed to achieve this goal is:

a) The use of deep learning tools, which can

use the techniques of deep learning to improve the performance of

cognitive systems

b) The use of machine learning as a tool for image reconstruction

c) The use of machine learning as a tool for image reconstruction and training

d) The use of machine learning as a tool for image reconstruction and training

e) The use of machine learning as a tool for image reconstruction and training

f) The use of machine learning as a tool for image reconstruction and training

g) The use of machine learning as a tool for image reconstruction and training

h) The use of machine learning as a tool for image reconstruction and training

i) The use of machine learning as a tool for image reconstruction and training

j) The use of machine learning as a tool for image reconstruction and training

k) The use of machine learning as a tool for image reconstruction and training

l) The use of machine learning as a tool for image reconstruction and training

m) The use of machine learning as a tool for image reconstruction and training

n) The use of machine learning as a

In [61]:
type(generated_summary)

list

In [60]:
type (generated_summary[0])

dict

In [62]:
generated_summary[0] ["generated_text"]

'  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance in clinical and\npreclinical applications. To realize the full impact of machine learning on\nmedical imaging, major challenges must be addressed.\n\nThe approach that is needed to achieve this goal is:\n\na) The use of deep learning tools, which can\n\nuse the techniques of deep learning to improve the performance of\n\ncognitive systems\n\nb) The use of machine learning as a tool for image reconstruction\n\nc) The use of machine learning as a tool for image reconstruction and training\n\nd) The use of machine learning as a tool for image reconstruction and training\n\ne) The use of machine learning as a tool for image reconstruction and training\n\nf) The use of machine learning as a tool for image reconstruction and training\n\ng) The use of machine learning as a tool for image reconstruction and training\n\nh) The use of machine learning as a tool for image reconstruction and training\n\ni) The use of machine learning as a tool for image reconstruction and training\n\nj) The use of machine learning as a tool for image reconstruction and training\n\nk) The use of machine learning as a tool for image reconstruction and training\n\nl) The use of machine learning as a tool for image reconstruction and training\n\nm) The use of machine learning as a tool for image reconstruction and training\n\nn) The use of machine learning as a'

In [63]:
 for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Abstract (first 500 chars)",df.iloc[idx]['abstract'][:500])

    generated_summary = text_generator(df.iloc[idx]["abstract"], max_length=120, min_length=40, num_return_sequences=1, truncation=True)
    summary_text = generated_summary[0]["generated_text"]
    print("Generated Summary:", summary_text)
    print()

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Abstract (first 500 chars)   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

Image classification

Image classification is a technique for performing classification of complex stimuli (or

intelligences) using the

decomposition of images into discrete or

quadratic-valued domains.

The techniques used are, for first time, new

technologies for image classification, which are designed to

provide a new way in which images are decoded into a

domain-specific

domain. The

structure of the

image classification scheme

are summarized in the following diagram.

FIG. 1

FIG. 2

FIG. 3

FIG. 4

FIG. 5

FIG. 6

FIG. 7

FIG. 8

FIG. 9

FIG. 10

FIG. 11

FIG. 12

FIG. 13

FIG. 14

Fig. 15

FIG. 16

FIG. 17

FIG. 18

FIG. 19

FIG. 20

FIG. 21

FIG. 22

FIG. 23

FIG. 24

FIG. 25

FIG. 26

FIG. 27

FIG. 28



Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract (first 500 chars)   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following central question in the context of medical image
analysis: \emph{Can the use of pre-trained deep CNNs with sufficient
fine-tuning eliminate the need for training a deep CNN from scratch?} To
address this question, we considered 4 distinct medical imaging applications in
3 specialties (radiology, cardiology, and gastroenterology) involving
classification, detection, and segmentation from 3 different imaging
modalities, and investigated how the performance of deep CNNs trained from
scratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.
Our experiments consistently demonstrated that (1) the use of a pre-trained CNN
with adequate fine-tuning outperformed or, in the worst case, performed as well
as a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size
of training sets than CNNs trained from scratch; (3) neither shallow tuning nor
deep tuning was the optimal choice for a particular application; and (4) our
layer-wise fine-tuning scheme could offer a practical way to reach the best
performance for the application at hand based on the amount of available data.
 of an ImageNet model of a medical-image dataset allow for the integration of

medial and nonmedical images?

1. What is a Medical ImageNet model?

It is an ImageNet model which is analogous to the ImageNet that is used in some

medical image analysis. It is a dataset of unprocessed data that contains a large number of

differentially labeled images. The dataset is typically composed of tens of thousands of images

that have been trained with training data that are not labeled. Each image that has been

trained has a different name and its value and its size. The training dataset is

created by taking the same set of images from each of the training dataset,

and applying the new name to a set of images that have been trained. The training

datasets are then sorted by the training data, and the resulting training

data is used to train and optimize the medical image.

2. What is a Medical ImageNet?

The medical image analysis technique is similar to the neural network used to

train an image. However, it is not as powerful as the neural network used

to train an image. Rather, the medical image analysis

Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Abstract (first 500 chars)   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the training of the network, and to the
limited understanding of their relevance. Since an exhaustive search is not
tractable, we propose to optimize the network first by random search, and then
by an adaptive search based on Gaussian Processes and Probability of
Improvement. Applying this method on a large and varied MRI dataset, we show a
substantial improvement between the baseline network and the final one (up to
20\% for the most difficult classes).
 search for the best solution
is needed to solve the problem, the training of the network is the most practical.

Learning

The training process is the most important step in the development of a virtual reality system, and can be

often the most difficult. The training process should be followed by the training of the system and the user in

a way that maximizes the training time. As the user experiences the training process, the

image may be altered, and the training may result in changes of image quality, like a small percentage of

images.

The training of the network involves several steps:

a) Preprocessing. The training process is done in a single step, and it is

only necessary for the training of the network if the training is done by the user.

b) Training. The training process is done in a single step, and it is only necessary for the training of the

network if the training is done by the user. c) Classification. The training process is done in a single step, and it is only necessary

for the training of the network if the training is done by the user. d) Evaluation. The training is done in a single step, and

Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Abstract (first 500 chars)   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generated Summary:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. This difference makes it inadequate to use
the existing network architectures developed for natural images, because they
work on heavily downscaled images to reduce the memory requirements. This hides
details necessary to make accurate predictions. Additionally, a single exam in
medical imaging often comes with a set of views which must be fused in order to
reach a correct conclusion. In our work, we propose to use a multi-view deep
convolutional neural network that handles a set of high-resolution medical
images. We evaluate it on large-scale mammography-based breast cancer screening
(BI-RADS prediction) using 886,000 images. We focus on investigating the impact
of the training set size and image size on the prediction accuracy. Our results
highlight that performance increases with the size of training set, and that
the best performance can only be achieved using the original resolution. In the
reader study, performed on a random subset of the test set, we confirmed the
efficacy of our model, which achieved performance comparable to a committee of
radiologists when presented with the same data.
 account for the degree of precision in
sparse images. However, the basic technique used to detect images with low quality is a well-known technique called

deep learning. It has been shown to be effective in detecting

lots of medical images with low quality, and is now being used in a wide range of

medical imaging applications. Deep learning can be applied to many different kinds of images, including

lots of medical images, and is a promising new approach to the detection of many

clinical features.

The main reasons for the rapid popularity of deep learning are the

consequences on image quality of the existing network architectures. In addition,

the new algorithms used to detect medical images with low quality

have also been compared to traditional neural networks, which take advantage of

the properties of deep convolutional networks and the fact that the data are very

large. These results show that deep learning can be applied to many different types of

images, including medical images, so it is a powerful approach to understanding

of all kinds of images.

There are some limitations of the process, as well as some questions about its

application. For example, the current network architectures

Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Abstract (first 500 chars)   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar
Generated Summary:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN architecture and classification accuracy for the
original images of lung nodules. In order to understand the features of lung
nodules, we further construct new datasets, based on the combination of
artificial geometric nodules and some transformations of the original images,
as well as a stochastic nodule shape model. It is found that simplistic
geometric nodules cannot capture the important features of lung nodules.
 in a single epoch. We show that the CNN architecture is fully functional and

operational, and that it minimizes the need for an extractor. We conclude that the CNN architecture is effective for

the classification of lung nodules in a single epoch, and that it minimizes the need for an extractor. We conclude that the CNN architecture is

effective for the classification of lung nodules in a single epoch.

In summary, our findings suggest that deep recurrent neural networks can overcome the

weakness of the traditional methods of classification and classification accuracy for the thoracic CT image.

Materials and Methods Data Acquisition and Analysis SPSS version 9.0 (SPSS Inc., Chicago, IL) was used. Data were collected at 2,000 Hz by a

n = 1373.8 undergraduate students and were analyzed using the V.I.S. statistical software, version 6 (version 10.0, version 4.5)

(V.I.S. University of Illinois, Chicago, IL). Data were processed using SPSS v. 8.0.5, version 9.0.3, and v. 8.0.2 (V.I.S., University

In [64]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Title",df.iloc[idx]['abstract'][:500])
    print()
    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40,do_sample=False)
    print(summary)
    print(summary[0] ["summary_text"] )
    print()

In [65]:
!pip install keybert==0.8.5

Requirement already satisfied: keybert==0.8.5 in /usr/local/lib/python3.12/dist-packages (0.8.5)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (5.12.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (1.20.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.25.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert==0.8.5) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.0.3)

In [66]:
from keybert import KeyBERT

In [67]:
kw_model = KeyBERT(model)

In [68]:
type(kw_model)#model= SentenceTransformer("all-MiniLM-L6-v2")

keybert._model.KeyBERT

In [69]:
text=df.iloc[10466]["abstract"]
keywords=kw_model.extract_keywords(text)

In [70]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [71]:
print(type(keywords))

<class 'list'>

In [72]:
print(type(keywords[0]))

<class 'tuple'>

In [73]:
kw_model.extract_keywords(text,keyphrase_ngram_range=(1,1),stop_words="english")

[('imaging', 0.4528),
 ('tomographic', 0.4488),
 ('reconstruction', 0.3623),
 ('deep', 0.3003),
 ('learning', 0.2622)]

In [74]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [75]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score, idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title", df.iloc[idx]['title'])
    print("Title",df.iloc[idx]['abstract'][:500])
    print()
    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40,do_sample=False)
    print(summary)
    print(summary[0] ["summary_text"] )
    print()
    kw_model.extract_keywords(text,keyphrase_ngram_range=(1,1),stop_words="english")
    print(keywords)
    for k,s in keywords:
      print(K)

In [76]:
!pip install fastapi uvicorn nest-asyncio

Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (0.138.0)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (0.49.0)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (1.3.1)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (2.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.0.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (8.4.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (2.46.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.18)

In [77]:
# Save the processed DataFrame to a pickle file for FastAPI to load
df.to_pickle('df.pkl')

In [78]:
%%writefile main.py
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import nest_asyncio
import pandas as pd
import numpy as np
import faiss
import os
from sentence_transformers import SentenceTransformer
from transformers import pipeline

# --- Load NLP resources ---

df = pd.DataFrame() # Initialize empty DataFrame
try:
    if os.path.exists("df.pkl"):
        df = pd.read_pickle("df.pkl")
        if "paper_text" not in df.columns:
            df["paper_text"] = df["title"] + df["abstract"]
            df["paper_text"] = df["paper_text"].str.replace("\\n", " ", regex=False)
            df["paper_text"] = df["paper_text"].str.strip()
except Exception as e:
    print(f"Error loading DataFrame: {e}")

model = None
try:
    model = SentenceTransformer("all-MiniLM-L6-v2")
except Exception as e:
    print(f"Error loading SentenceTransformer model: {e}")

# Initialize the text-generation pipeline as a workaround for summarization
text_generator = None
try:
    text_generator = pipeline("text-generation", model="gpt2")
    print("Text generation pipeline initialized successfully in FastAPI!")
except Exception as e:
    print(f"Error loading text-generation pipeline: {e}")

index = None
try:
    if os.path.exists("paper_faiss.index"):
        index = faiss.read_index("paper_faiss.index")
except Exception as e:
    print(f"Error loading FAISS index: {e}")

app = FastAPI()

class QueryRequest(BaseModel):
    query: str
    k: int = 5

@app.get("/shard")
async def root():
    return {"message": "Hello from FastAPI!"}

@app.post("/search_and_summarize/")
async def run_search_and_summarize(request: QueryRequest):
    if model is None or text_generator is None or index is None or df.empty:
        raise HTTPException(status_code=503, detail="NLP resources not loaded. Server is not ready.")

    results = []
    try:
        query_embedding = model.encode([request.query])
        faiss.normalize_L2(query_embedding)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error encoding query: {e}")

    try:
        D, I = index.search(query_embedding, request.k)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error performing FAISS search: {e}")

    for score, idx in zip(D[0], I[0]):
        try:
            if idx >= len(df):
                continue

            abstract_text = df.iloc[idx]['abstract']

            summary_text = "Summarizer not available."
            if text_generator:
                # Use text_generator for summarization
                generated_summary = text_generator(
                    abstract_text,
                    max_length=120,
                    min_length=40,
                    num_return_sequences=1,
                    truncation=True
                )
                summary_text = generated_summary[0]["generated_text"]

            results.append({
                "score": float(score),
                "title": df.iloc[idx]['title'],
                "abstract_snippet": abstract_text[:500] + "...",
                "summary_text": summary_text,
            })
        except IndexError:
            pass
        except Exception as e:
            print(f"Error processing result for index {idx}: {e}")
            continue

    return {"query": request.query, "results": results}

Overwriting main.py

In [79]:
import uvicorn
import nest_asyncio
import threading
import time
from main import app

nest_asyncio.apply()

def run_fastapi_threaded():
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="error", reload=False)

fastapi_thread = threading.Thread(target=run_fastapi_threaded)
fastapi_thread.daemon = True
fastapi_thread.start()
time.sleep(5)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Text generation pipeline initialized successfully in FastAPI!

In [80]:
import requests

response = requests.get("http://localhost:8000/shard")
print(response.json())

query_data = {"query": "deep learning in medical imaging", "k": 3}
response = requests.post("http://localhost:8000/search_and_summarize/", json=query_data)
print(response.json())

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'message': 'Hello from FastAPI!'}

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'query': 'deep learning in medical imaging', 'results': [{'score': 0.7354985475540161, 'title': 'A Perspective on Deep Imaging', 'abstract_snippet': '  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance...', 'summary_text': '  The combination of tomographic imaging and deep learning, or machine learning\nin general, promises to empower not only image analysis but also image\nreconstruction. The latter aspect is considered in this perspective article\nwith an emphasis on medical imaging to develop a new generation of image\nreconstruction theories and techniques. This direction might lead to\nintelligent utilization of domain knowledge from big data, innovative\napproaches for image reconstruction, and superior performance in clinical and\npreclinical applications. To realize the full impact of machine learning on\nmedical imaging, major challenges must be addressed.\n\n1. The first approach will be to integrate machine learning into the design of\n\ncomputer vision systems. Such systems will consist of a single camera, the sensor, and a software system that\n\nuses a combination of machine-learning and deep learning to map and generate\n\nimage-related images. The system will then use image transformations to interpret and\n\ninterpret the image, which may involve image modeling and image processing.\n\n2. The third approach will be to integrate machine learning and deep learning into the design of\n\ncomputer vision systems. Such systems will consist of a single camera, the sensor, and a software system that\n\nuses a combination of machine-learning and deep learning to map and generate image-related images. The\n\nsystem will then use image transformations to interpret and interpret the image, which may involve image modeling and\n\nimage processing.\n\n3. The fourth approach will be to integrate machine learning and deep learning into the design of\n\ncomputer vision systems. Such systems will consist of a single camera, the sensor, and a\n\nsoftware system that uses a combination of machine-learning and deep learning to map and generate\n\nimage-related images. The system will then use image transformations to interpret and interpret\n'}, {'score': 0.6881735920906067, 'title': 'Classification of MRI data using Deep Learning and Gaussian\n  Process-based Model Selection', 'abstract_snippet': '  The classification of MRI images according to the anatomical field of view is\na necessary task to solve when faced with the increasing quantity of medical\nimages. In parallel, advances in deep learning makes it a suitable tool for\ncomputer vision problems. Using a common architecture (such as AlexNet)\nprovides quite good results, but not sufficient for clinical use. Improving the\nmodel is not an easy task, due to the large number of hyper-parameters\ngoverning both the architecture and the trai...', 'summary_text': '  The classification of MRI images according to the anatomical field of view is\na necessary task to solve when faced with the increasing quantity of medical\nimages. In parallel, advances in deep learning makes it a suitable tool for\ncomputer vision problems. Using a common architecture (such as AlexNet)\nprovides quite good results, but not sufficient for clinical use. Improving the\nmodel is not an easy task, due to the large number of hyper-parameters\ngoverning both the architecture and the training of the network, and to the\nlimited understanding of their relevance. Since an exhaustive search is not\ntractable, we propose to optimize the network first by random search, and then\nby an adaptive search based on Gaussian Processes and Probability of\nImprovement. Applying this method on a large and varied MRI dataset, we show a\nsubstantial improvement between the baseline network and the final one (up to\n20\\% for the most difficult classes).\n meta-analysis of 50\n\nhigh-order models\n\n(1, 2)\n\nCitation:\n\nCranney, A.S., D.T.S., and J.C.D.\n\nA common architecture (A) and the training of a deep neural network (C)\n\nprovides good results for clinical, behavioral, and imaging imaging problems.\n\nAbstract:\n\nThe classification of MRI images according to the anatomical field of view (D) improves\n\nthe diagnosis and treatment of low-level clinical problems, including brain injury, head injury,\n\nbrain trauma, and other neurodegenerative conditions.\n\nBackground: The classification of MRI images according to the anatomical field of view (D) facilitates\n\nthe acquisition of clinically relevant anatomical images. With the use of this architecture, the\n\nimaging problem is substantially improved after a single training session in deep-learning\n\nprocessing.\n\nMethods:\n\nA parallel, high-level network of five (5) functional MRI images was trained on a single functional\n\nimage classification algorithm (PAS) (1). A single task was chosen for each image image.\n\nResults:\n\nThe training dataset (in a'}, {'score': 0.6532081961631775, 'title': 'Convolutional Neural Networks for Medical Image Analysis: Full Training\n  or Fine Tuning?', 'abstract_snippet': '  Training a deep convolutional neural network (CNN) from scratch is difficult\nbecause it requires a large amount of labeled training data and a great deal of\nexpertise to ensure proper convergence. A promising alternative is to fine-tune\na CNN that has been pre-trained using, for instance, a large set of labeled\nnatural images. However, the substantial differences between natural and\nmedical images may advise against such knowledge transfer. In this paper, we\nseek to answer the following centra...', 'summary_text': '  Training a deep convolutional neural network (CNN) from scratch is difficult\nbecause it requires a large amount of labeled training data and a great deal of\nexpertise to ensure proper convergence. A promising alternative is to fine-tune\na CNN that has been pre-trained using, for instance, a large set of labeled\nnatural images. However, the substantial differences between natural and\nmedical images may advise against such knowledge transfer. In this paper, we\nseek to answer the following central question in the context of medical image\nanalysis: \\emph{Can the use of pre-trained deep CNNs with sufficient\nfine-tuning eliminate the need for training a deep CNN from scratch?} To\naddress this question, we considered 4 distinct medical imaging applications in\n3 specialties (radiology, cardiology, and gastroenterology) involving\nclassification, detection, and segmentation from 3 different imaging\nmodalities, and investigated how the performance of deep CNNs trained from\nscratch compared with the pre-trained CNNs fine-tuned in a layer-wise manner.\nOur experiments consistently demonstrated that (1) the use of a pre-trained CNN\nwith adequate fine-tuning outperformed or, in the worst case, performed as well\nas a CNN trained from scratch; (2) fine-tuned CNNs were more robust to the size\nof training sets than CNNs trained from scratch; (3) neither shallow tuning nor\ndeep tuning was the optimal choice for a particular application; and (4) our\nlayer-wise fine-tuning scheme could offer a practical way to reach the best\nperformance for the application at hand based on the amount of available data.\n of image processing be done at the state-of-the-art level\n\nof the human brain?}\n\n\\begin{align}\n\n\\param {F}} A neural network is a set of structures that, when\n\nprocessed, generate a set of images that are represented as\n\nfictitious images in the context of the image processing.\n\nWhen processing a neural network, it must not only be able to generate\n\nfictitious images, but also be able to reconstruct them. When processing\n\na neural network, it must also be able to reconstruct images that it\n\nhas previously captured, not only at the state-of-the-art level, but at the\n\ninstantaneous level. This allows for a much faster, and more efficient\n\nprocessing of the neural network.\n\nIt seems clear that images generated by neural networks are not always\n\nfictitious, but rather, they are sometimes manipulated in a way that\n\nreproduces images that are not fictitious. In this paper, we introduce\n\nthis possibility and demonstrate a possible solution for this problem.\n\nThe neural network generated by the CNN is a set of images\n\nthat are not fict'}]}